# Generated by Django 4.0.1 on 2022-01-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('machine_code', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=12)),
                ('priority_type', models.CharField(max_length=12)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('hour_arrive', models.TimeField(auto_now_add=True)),
                ('issue_description', models.CharField(max_length=150)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisicao.factory')),
            ],
        ),
    ]
